server:
  port: 5010

spring:
  application:
    name: auth-resource-5010

logging:
  level:
    com.koubs.spring.auth: debug
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/userinf
