spring:
  application:
    name: consumer-feign-hystrix-order
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true

server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.atguigu.springcloud: debug

# 用于服务降级在注解 @FeignClient 中添加 fallbackFactory 属性值
feign:
  hystrix:
    enabled: true
