spring:
  application:
    name: CLOUD-GATEWAY

server:
  port: 9528

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

zuul:
  # 不希望系统自动映射的路由被外部使用时，* 代表所有的自动映射不被外部使用
  #  ignored-services: cloud-payment-service,cloud-gateway
  ignored-services: "*"
  # 在各个服务请求地址上添加一个前缀用来标识模块和子系统是一项最佳实践. / 不可少
  prefix: /koubs
  routes:
    cloud-payment-service: payment/**
    thirdpartyservice:
      path: /thirdpartyservice/**
      url: http://news.baidu.com

#ribbon:
#  eureka:
#    enabled: false
