###consul服务端口号
server:
  port: 8007

spring:
  application:
    name: consul-provider-service
####consul注册中心地址
  cloud:
    consul:
      host: 121.37.20.182
      port: 58500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}



