server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.181.124:8848 #配置 Nacos 地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


